# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ZufuWbEKcjVFWIv94T6gBT-OMIajyeT
"""

# ==========================================================
# AI DAMAGE & RECONSTRUCTION DEMO
# Shows only Damaged Image and Reconstructed Image
# ==========================================================

!pip -q install simple-lama-inpainting --no-deps
!pip -q install fire pyyaml pydantic

from google.colab import files
from simple_lama_inpainting import SimpleLama
from PIL import Image
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Upload image
print("Upload Image")
uploaded = files.upload()

image_path = list(uploaded.keys())[0]

# Read image
img = cv2.imread(image_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

h, w = img.shape[:2]

# --------------------------------
# Create slight shirt damage
# --------------------------------
damage_mask = np.zeros((h, w), dtype=np.uint8)

center_x = int(w * 0.50)
center_y = int(h * 0.58)

cv2.ellipse(
    damage_mask,
    (center_x, center_y),
    (25, 35),
    15,
    0,
    360,
    255,
    -1
)

# Damaged image
damaged_img = img_rgb.copy()
damaged_img[damage_mask == 255] = [0, 0, 0]

# --------------------------------
# AI Reconstruction
# --------------------------------
lama = SimpleLama()

reconstructed = lama(
    Image.fromarray(damaged_img),
    Image.fromarray(damage_mask)
)

reconstructed = np.array(reconstructed)

# --------------------------------
# Display Results
# --------------------------------
fig, ax = plt.subplots(1, 2, figsize=(14, 6))

ax[0].imshow(damaged_img)
ax[0].set_title("SLIGHTLY DAMAGED IMAGE", fontsize=14)

ax[1].imshow(reconstructed)
ax[1].set_title("AI RECONSTRUCTED IMAGE", fontsize=14)

for a in ax:
    a.axis("off")

plt.tight_layout()
plt.show()

# --------------------------------
# Report
# --------------------------------
print("\n====================================")
print(" AI RECONSTRUCTION REPORT")
print("====================================")
print("Damage Type       : Minor Shirt Damage")
print("AI Model          : LaMa Inpainting")
print("Restoration Mode  : Generative Fill")
print("Status            : SUCCESS")
print("====================================")